#!/usr/bin/env ruby
require 'rubygems'

if defined?(Pry)
  Pry.commands.alias_command 'c', 'continue'
  Pry.commands.alias_command 's', 'step'
  Pry.commands.alias_command 'n', 'next'
end

begin
  require 'awesome_print'
rescue LoadError
else
  AwesomePrint.pry!
end
