#!/usr/bin/env ruby

Pry.config.pager = false
Pry.config.commands.alias_command 'c', 'continue'
Pry.config.commands.alias_command 's', 'step'
Pry.config.commands.alias_command 'n', 'next'

begin
  require 'awesome_print'
rescue LoadError
else
  AwesomePrint.pry!
end
