#!/usr/bin/env sh
# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/bin" ]] ; then
	PATH="$HOME/bin:$PATH"
fi

if [[ -d "$HOME/.files/bin" ]] ; then
	PATH="$HOME/.files/bin:$PATH"
fi

source "$HOME/.alias"

# git
export GIT_SSH="$HOME/bin/git-ssh"

## Editor
if [[ -s $(which vimr) ]]; then
	export VISUAL='vimr -s'
elif [[ -s $(which gnvim) ]]; then
	export VISUAL=gnvim
elif [[ -s $(which mvim) ]]; then
	export VISUAL=mvim
fi

if [[ -s $(which nvim) ]]; then
	export EDITOR=nvim
else
	export EDITOR=vim
fi

# java
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"

# go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH # shiftin GOPATH bins


# added by travis gem
[ -f /Users/jlane/.travis/travis.sh ] && source /Users/jlane/.travis/travis.sh

# chruby
[ -f /usr/local/share/chruby/chruby.sh ] && source /usr/local/share/chruby/chruby.sh
[ -f /usr/local/share/chruby/auto.sh ] && source /usr/local/share/chruby/auto.sh
[ -f /usr/local/opt/chruby/share/chruby/chruby.sh ] && source /usr/local/opt/chruby/share/chruby/chruby.sh
[ -f /usr/local/opt/chruby/share/chruby/auto.sh ] && source /usr/local/opt/chruby/share/chruby/auto.sh

if type chruby > /dev/null; then
	chruby 2.4.2 2>/dev/null
fi

# keys
if [[ -s $(which keychain) ]]; then
	eval `keychain -q --eval --agents ssh --inherit any ~/.ssh/id_rsa ~/.ssh/fastly.id_rsa`
	source ~/.keychain/$HOST-sh
	source ~/.keychain/$HOST-sh-gpg
else
	ssh-add -A ~/.ssh/id_rsa &>/dev/null
fi

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
