#!/bin/sh
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
[ -f /usr/local/etc/profile.d/z.sh ] && . /usr/local/etc/profile.d/z.sh
# macos
[ -f /usr/local/opt/chruby/share/chruby/chruby.sh ] && . /usr/local/opt/chruby/share/chruby/chruby.sh
# arch
[ -f /usr/share/chruby/chruby.sh ] && . /usr/share/chruby/chruby.sh

# macos
[ -f /usr/local/opt/chruby/share/chruby/auto.sh ] && . /usr/local/opt/chruby/share/chruby/auto.sh
# arch
[ -f /usr/share/chruby/auto.sh ] && . /usr/share/chruby/auto.sh

if command -v rbenv >/dev/null; then
	eval "$(rbenv init -)"
elif command -v chruby >/dev/null; then
	chruby 2.6.3
fi
