#!/usr/bin/env sh
# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/bin" ]] ; then
	PATH="$HOME/bin:$PATH"
fi

if [[ -d "$HOME/.files/bin" ]] ; then
	PATH="$HOME/.files/bin:$PATH"
fi

source "$HOME/.alias"

# git
export PATH="$HOME/sbin:/usr/local/bin:$PATH:/usr/local/git/bin:/usr/local/sbin"
export GIT_SSH="$HOME/bin/git-ssh"

## Editor
if [[ -s $(which mvim) ]]; then
	export EDITOR=mvim
	export VISUAL=mvim
else
	export EDITOR=vim
	export VISUAL=vim
fi

# java
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"

# go
export PATH=$GOPATH/bin:$PATH # shiftin GOPATH bins
export GOPATH=$HOME/go


# added by travis gem
[ -f /Users/jlane/.travis/travis.sh ] && source /Users/jlane/.travis/travis.sh

# chruby
[ -f /usr/local/share/chruby/chruby.sh ] && source /usr/local/share/chruby/chruby.sh
[ -f /usr/local/share/chruby/auto.sh ] && source /usr/local/share/chruby/auto.sh
[ -f /usr/local/opt/chruby/share/chruby/chruby.sh ] && source /usr/local/opt/chruby/share/chruby/chruby.sh
[ -f /usr/local/opt/chruby/share/chruby/auto.sh ] && source /usr/local/opt/chruby/share/chruby/auto.sh

if [[ -s $(which chruby) ]]; then
	chruby 2.3
fi

if [[ -s $(which keychain) ]]; then
	eval `keychain -q --eval --agents ssh --inherit any ~/.ssh/id_rsa ~/.ssh/fastly.id_rsa`
	source ~/.keychain/$HOST-sh
	source ~/.keychain/$HOST-sh-gpg
fi

