#!/usr/bin/env sh

# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/bin" ]]; then
	PATH="$HOME/bin:$PATH"
fi

# xdg-derived, systemd file-hierarchy
if [[ -d "$HOME/.local/bin" ]]; then
	PATH="$HOME/.local/bin:$PATH"
fi

if [[ -d "$HOME/.files/bin" ]]; then
	PATH="$HOME/.files/bin:$PATH"
fi

source "$HOME/.alias"

# git
export GIT_SSH="$HOME/bin/git-ssh"

unset EDITOR
unset EDITORD

if [[ -s $(which nvim) ]]; then
	export EDITOR=nvim
elif [[ -s $(which vim) ]]; then
	export EDITOR=vim
else
	export EDITOR=vi
fi

export EDITORD=${EDITORD:-$EDITOR}

# go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH # shiftin GOPATH bins

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# keys
KEYCHAIN=${SSH_KEYS:-"${HOME}/.ssh/id_rsa"}
if [[ -s $(which keychain) ]]; then
	if [[ $(uname) == 'Linux' ]]; then
		eval $(keychain -q --eval --agents ssh $KEYCHAIN)
	else
		eval $(keychain -q --eval --agents ssh --inherit any $KEYCHAIN)
	fi
	[ -f ~/.keychain/$HOST-sh ] && source ~/.keychain/$HOST-sh
	[ -f ~/.keychain/$HOST-sh-gpg ] && source ~/.keychain/$HOST-sh-gpg
else
	ssh-add -A ~/.ssh/id_rsa &>/dev/null
fi

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
[ -f /usr/local/etc/profile.d/z.sh ] && . /usr/local/etc/profile.d/z.sh
# macos
[ -f /usr/local/opt/chruby/share/chruby/chruby.sh ] && . /usr/local/opt/chruby/share/chruby/chruby.sh
# arch
[ -f /usr/share/chruby/chruby.sh ] && . /usr/share/chruby/chruby.sh

# macos
[ -f /usr/local/opt/chruby/share/chruby/auto.sh ] && . /usr/local/opt/chruby/share/chruby/auto.sh
# arch
[ -f /usr/share/chruby/auto.sh ] && . /usr/share/chruby/auto.sh

if [[ -s $(type chruby) ]]; then
	chruby 2.6.0
fi

# vim: set ft=sh:
