#! /bin/sh

sxhkd &
~/.config/polybar/launch.sh 2>&1 1>~/.config/polybar/polybar.log &
xscreensaver-command -exit
xscreensaver &
xss-lock -- /usr/bin/xscreensaver-command -lock &
source ~/.xsession

xsetroot -solid "#262626"

bspc monitor -d I II III

bspc config border_width         1
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"
bspc config active_border_color "#E84F4F"

# It looks like these options get overridden by Compton...
bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75
