#! /bin/sh

source ~/.xsession
xsetroot -solid "#262626"

sxhkd 2>&1 > ~/.config/sxhkd/sxhkd.log &
~/.config/polybar/launch.sh 2>&1 1>~/.config/polybar/polybar.log &

bspc monitor eDP1 -d a b c d
bspc monitor DP1 -d a b c d
bspc monitor DP2 -d a b c d

bspc config border_width         2
bspc config window_gap           15
bspc config split_ratio          0.52 # ( 1 + sqrt(5) / 6 ) - 0.11
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config normal_border_color  "#262626"
bspc config focused_border_color "#7aa2f7"
bspc config urgent_border_color  "#e0af68"
bspc config presel_border_color  "#ad8ee6"
bspc config active_border_color  "#449dab"

bspc monitor DP1 --rectangle 3840x2160+0+0
bspc monitor DP2 --rectangle 3840x2160+0+0
bspc config merge_overlapping_monitors false

XSECURELOCK_DIM_COLOR="#1a1b26" \
	XSECURELOCK_PASSWORD_PROMPT=emoticon \
	XSECURELOCK_SHOW_HOSTNAME=0 \
	XSECURELOCK_SHOW_USERNAME=0 \
	XSECURELOCK_FONT="Hack Nerd Font Mono" \
	xss-lock -n /usr/lib/xsecurelock/saver_xscreensaver -l -- xsecurelock
