#! /bin/sh

source ~/.xsession
xsetroot -solid "#262626"

sxhkd &
~/.config/polybar/launch.sh 2>&1 1>~/.config/polybar/polybar.log &

bspc monitor eDP1 -d a b c d
bspc monitor DP1 -d a b c d
bspc monitor DP2 -d a b c d

bspc config border_width         2
bspc config window_gap           15
bspc config split_ratio          0.52 # ( 1 + sqrt(5) / 6 ) - 0.11
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config normal_border_color  "#363636"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color  "#B58900"
bspc config presel_border_color  "#26E2FF"
bspc config active_border_color  "#E84F4F"

bspc monitor DP1 --rectangle 3840x2160+0+0
bspc monitor DP2 --rectangle 3840x2160+0+0
bspc config merge_overlapping_monitors false

XSECURELOCK_DIM_COLOR="#262626" XSECURELOCK_PASSWORD_PROMPT=time_hex XSECURELOCK_FONT="Hack Nerd Font Mono" xss-lock -n /usr/lib/xsecurelock/saver_xscreensaver -l -- xsecurelock
