require("hop").setup()

vim.keymap.set("n", "<leader><leader>w", "<cmd>:HopWord<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader><leader>b", "<cmd>:HopWordBC<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader><leader>f", "<cmd>:HopWordAC<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader><leader>l", "<cmd>:HopLineStart<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader><leader>j", "<cmd>:HopLineStartAC<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader><leader>k", "<cmd>:HopLineStartBC<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader><leader>c", "<cmd>:HopLine<CR>", { noremap = true, silent = true })
vim.keymap.set("n", ";", "<cmd>:HopPattern<CR>", { noremap = true, silent = true })
