#!/usr/bin/env /bin/bash
set -x

DOTFILES=$1

cd ~

if [ -d ~/.oh-my-zsh ]; then
	cd .oh-my-zsh && git pull origin master
else
	git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

if [ -d ~/.oh-my-zsh/custom/themes/powerlevel9k ]; then
	cd ~/.oh-my-zsh/custom/themes/powerlevel9k && git pull origin master
else
	git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
fi

cd ~
