#!/usr/bin/env /bin/bash
set -x

DOTFILES=$1

pushd ~

if [ -d '.oh-my-zsh' ]; then
  cd .oh-my-zsh && git pull origin master;
else
  git clone git://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh
fi
popd
