# /etc/zshenv: user specific .zshenv file for zsh(1).
#
# Sourced on all invocations of the shell.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

export OS=`uname -s`

export EDITOR="vim"
export PAGER="less"
export LESS="-RMin"
export EMAIL="me@joshualane.com"
export ARCH=`uname -m`

export IRCNICK='lanej'
export IRCSERVER='irc.freenode.net'

export SAVEHIST=9999
export HISTSIZE=9999
export HISTFILE=$HOME/.history
export HIST_EXPIRE_DUPS_FIRST=true

 # Ruby tweaks
 export RUBY_GC_MALLOC_LIMIT=1000000000
 export RUBY_FREE_MIN=500000
 export RUBY_HEAP_MIN_SLOTS=40000
