# /etc/zshenv: user specific .zshenv file for zsh(1).
#
# Sourced on all invocations of the shell.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

export OS=`uname -s`

export EDITOR="vim"
export PAGER="less"
export LESS="-RMin"
export EMAIL="me@joshualane.com"
export ARCH=`uname -m`

export IRCNICK='lanej'
export IRCSERVER='irc.freenode.net'

export SAVEHIST=2000
export HISTSIZE=9999
export HISTFILE=$HOME/.history
export HIST_EXPIRE_DUPS_FIRST=true
