#!/bin/zsh
setopt inc_append_history
setopt extended_history
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_expire_dups_first
setopt hist_ignore_space

unsetopt nomatch
unsetopt share_history
unsetopt correct_all

bindkey -v # vi-mode

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
bindkey '^s' history-incremental-search-forward
bindkey '^e' end-of-line
bindkey '^a' beginning-of-line

autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# prompt
if command -v starship >/dev/null; then
	eval "$(starship init zsh)"
	[[ -r "${HOME}/.local/share/z/z.sh" ]] && source "${HOME}/.local/share/z/z.sh"
	[[ -r "${HOME}/.z.zsh" ]] && source "${HOME}/.z.zsh"
	if [[ -r "${HOME}/.local/share/zsh/autosuggestions/zsh-autosuggestions.zsh" ]]; then
    source "${HOME}/.local/share/zsh/autosuggestions/zsh-autosuggestions.zsh"
  fi
elif [[ -d "${HOME}/.oh-my-zsh" ]]; then
	plugins=(zsh-autosuggestions vi-mode z)
	typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=cyan
	typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=red
	typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='$'

	source "${HOME}/.oh-my-zsh/oh-my-zsh.sh"
fi

autoload -U select-word-style
select-word-style bash

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle :compinstall filename '/home/jlane/.zshrc'

autoload -Uz compinit
compinit

[[ -r "${HOME}/.config/zsh/fzf.zsh" ]] && source "${HOME}/.config/zsh/fzf.zsh"

. "${HOME}/.profile"
. "$HOME/.alias"
. "$HOME/.zlogin"
