#!/usr/bin/env fish
set -gx PATH /usr/local/bin /usr/sbin $HOME/bin $HOME/go/bin $HOME/google-cloud-sdk/bin $PATH

# git
set -gx GIT_SSH "$HOME/bin/git-ssh"

## editor
if which vimr > /dev/null
	set -Ux VISUAL 'vimr -s'
else if which gnvim > /dev/null
	set -Ux VISUAL gnvim
else if which mvim > /dev/null
	set -Ux VISUAL mvim
end

if which nvim > /dev/null
	set -Ux EDITOR nvim
else
	set -Ux EDITOR vim
end

set -Ux BUNDLER_EDITOR $VISUAL

set -Ux RI_PAGER 'less -RSX'

# fundle
if not functions -q fundle; eval (curl -sfL https://git.io/fundle-install); end

fundle plugin 'tuvistavie/fish-ssh-agent'
fundle plugin 'tuvistavie/oh-my-fish-core'
fundle plugin 'oh-my-fish/theme-bobthefish'
fundle plugin 'oh-my-fish/plugin-vi-mode'

fundle init

set fish_key_bindings fish_vi_key_bindings

# posix-source ~/.keys.env

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jlane/google-cloud-sdk/path.fish.inc' ]; if type source > /dev/null; source '/Users/jlane/google-cloud-sdk/path.fish.inc'; else; . '/Users/jlane/google-cloud-sdk/path.fish.inc'; end; end
set -g fish_user_paths "/usr/local/opt/libarchive/bin" $fish_user_paths
