#!/usr/bin/env bash
function fhr () {
  find . -iname "*$**"
}
function rd() {
    rdesktop -g 1400x900 $*
}
function svndif() {
    svn diff  --diff-cmd colordiff $* | less;
}
function find_in() {
    find . -iname $1 | xargs grep $2 -sl
}

function git-release() {
	git fetch origin -q
	local current_release=$(git tag -l 'v*' | sed -E 's/^v//g' | sort -g | tail -n 1)
	echo "Current release: v$current_release"
	local next_release=v$(( $current_release + 1 ))
	echo "Releasing: $next_release"
	git tag $next_release && git push origin $next_release
}

# bash
alias restart='sudo reboot'
alias shutdown='sudo halt'
alias apt-get='sudo apt-get'
alias root='sudo su -'
alias sp='source ~/.bash_profile'
alias nerd='vim +NERDTree'

# git
alias g="git"
alias gds='GIT_PAGER=cat git diff --stat'
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"

# ruby
alias b='bundle-hack'
alias bi='bundle-hack install'
alias be='bundle-exec-hack'
alias bl='bundle install --local'
alias guard='be guard'
alias r='be rspec'
alias rff='r --fail-fast'
alias reado="ssh-reagent $*"

alias enw='emacs -nw'
alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
alias v='vagrant'

alias untar='tar xvfz'
alias tfl='tail -Fn30 log/*.log'
alias c="clear"
alias retab="find . -iname '*.rb' | xargs sed -Ei '' 's/  /  /g'"
alias ey-meta='CLOUD_URL=https://cloud-meta.engineyard.com ey'
alias pt=papertrail
alias fucking='sudo'
alias k='kubectl'

alias rba='bundle exec rubocop -a'
alias pauper-start='chruby 2.0 && source ~/devel/activate && pauper start; chruby .'
