#!/usr/bin/env bash
function fhr () {
	find . -iname "*$**"
}
function rd() {
    rdesktop -g 1400x900 $*
}
function svndif() {
    svn diff  --diff-cmd colordiff $* | less;
}
function find_in() {
    find . -iname $1 | xargs grep $2 -sl
}
function gsfr () {
  git svn find-rev $1 | xargs git show
}
# bash
alias restart='sudo reboot'
alias shutdown='sudo halt'
alias apt-get='sudo apt-get'
alias root='sudo su -'
alias sp='source ~/.bash_profile'
alias svndif='svn diff --diff-cmd=colordiff'
alias nerd='vim +NERDTree'

# git
alias gs='git status -s'
alias gb='git branch'
alias grh="git reset --hard"
alias untar='tar xvfz'
alias gpl='git pull'
alias gl="git log --oneline --decorate --graph"
alias gsl="GIT_PAGER=cat git log -30 --oneline --decorate --graph"
alias gph='git push'
alias gpom='git push origin master'
alias gd='git diff'
alias gds='GIT_PAGER=cat git diff --stat'
alias gc='git commit'
alias gcv='git commit -v'
alias gca='git commit -av'
alias gaa='git add -A'
alias gco='git checkout'
alias gcl='git clone'
alias gb='git branch'
alias gs='git status -s'
alias grh='git reset --hard'
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"
alias pull='git pull origin master'
alias gf='git fetch'
alias gcav='git commit -av'
alias gcam='git commit -am'
#alias gsp="stashed=$(git stash save | test); git svn fetch && git svn rebase; test $stashed && git stash pop"

# git svn
alias gsf='git svn fetch'
alias gsr='git svn rebase'
alias gsp='git svn fetch; git stash save &> /dev/null; git svn rebase && git stash pop'
alias gsd='git stash save && git svn dcommit'

alias enw='emacs -nw'
alias gi='gem install'
alias b='bundle-hack'
alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
