## run for login shells

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

if [ -d "$HOME/.cinderalla" ]; then
  source $HOME/.cinderella.profile
fi

if [ -f "$HOME/.homebrew.profile" ]; then
  source $HOME/.homebrew.profile
fi
