#!/usr/bin/env sh
. ${HOME}/.bashrc

source ${HOME}/.alias

if [ -d "$HOME/etc/bash_completion.d" ] ; then
	. $HOME/etc/bash_completion.d/*.bash
fi

## Prompt
if [ -n "${SSH_CONNECTION+x}" ]; then
	export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"
else
	export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"
fi

[ -f "${HOME}/.fzf.bash" ] && . "${HOME}/.fzf.bash"
if [ -f "${HOME}/.local/share/z/z.sh" ]; then
	. "${HOME}/.local/share/z/z.sh"
	. "${HOME}/.z.sh"
fi
