#!/usr/bin/env /bin/bash
set -x
DOTFILES=$1

pushd $DOTFILES
if [ -d '.ssh_config' ]; then
  cd .ssh_config && git pull origin master;
else
  git clone git@github.com:engineyard/ssh-config .ssh_config
fi
popd

ln -fs ${DOTFILES}/.ssh_config/ssh_config ${HOME}/.ssh/config
